# Generated by Django 2.2.19 on 2021-04-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='qacpanelapp',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
